//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


TradeSide = {
'BUY' : 0,
'SELL' : 1,
'SHORT' : 2,
'COVER' : 3,
'SELL_TODAY' : 4,
'COVER_TODAY' : 5
};
